# Generated by Django 3.2.9 on 2021-11-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('ram', models.IntegerField()),
            ],
        ),
    ]
